# Skiapp Rollout (for Blue/Green Deployment)
# ------------------------------------------
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-demo-app
  namespace: team-riker
  labels:
    app: rollout-demo
spec:
  replicas: 3
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: rollout-demo
  template:
    metadata:
      labels:
        app: rollout-demo
    spec:
      containers:
      - name: rollout-demo
        image: argoproj/rollouts-demo:green
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
            requests:
                memory: "64Mi"
                cpu: "250m"
            limits:
                memory: "128Mi"
                cpu: "500m"
      {{ if .Values.spec.karpenterInstanceProfile }}
      nodeSelector: # <- add nodeselector, toleration and spread constraitns
        team: default
        type: karpenter
      tolerations:
        - key: 'karpenter'
          operator: 'Exists'
          effect: 'NoSchedule'
      {{ end }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: rollout-demo
      tolerations:
        - key: 'karpenter'
          operator: 'Exists'
          effect: 'NoSchedule'
  strategy:
    blueGreen:
      autoPromotionEnabled: false
      activeService: rollout-demo-svc
      previewService: rollout-demo-svc-preview
---
# Skiapp Service (Stable)
# -----------------------
apiVersion: v1
kind: Service
metadata:
  name: rollout-demo-svc
  namespace: team-riker
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: rollout-demo
---
# Skiapp Ingress (Stable)
# -----------------------
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-rollout-demo
  namespace: team-riker
  annotations:
    alb.ingress.kubernetes.io/group.name: riker
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    #alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    #alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=Riker
spec:
  ingressClassName: alb
  rules:
    - host: #skiapp.{{ .Values.spec.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rollout-demo-svc
                port:
                  number: 80
---
# Skiapp Service (Preview)
# -----------------------
apiVersion: v1
kind: Service
metadata:
  name: rollout-demo-svc-preview
  namespace: team-riker
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: rollout-demo
---
# Skiapp Ingress (Preview)
# -----------------------
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-rollout-demo-preview
  namespace: team-riker
  annotations:
    alb.ingress.kubernetes.io/group.name: riker-preview
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/tags: 'Environment=dev,Team=Riker'
spec:
  ingressClassName: alb
  rules:
  - host: 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rollout-demo-svc-preview
            port:
              number: 80
