apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-day-app
  labels:
    app: cloud-day-app
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: cloud-day-app
  template:
    metadata:
      labels:
        app: cloud-day-app
    spec:
      containers:
      - image: argoproj/rollouts-demo:green
        name: cloud-day-app
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: '50Mi'
            cpu: '50m'
          limits:
            memory: '50Mi'
            cpu: '50m'
        securityContext:
          privileged: false
          #readOnlyRootFilesystem: false # guestbook neet to write to /var/run/apache2/apache2.pid
          allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-day-app
  labels:
    app: cloud-day-app
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: cloud-day-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-guestbook
  # namespace is specified as namespace destination in env/{dev,test,prod}/team-riker.yaml
  labels:
    app: cloud-day-app
    {{- toYaml .Values.labels | nindent 4 }}
  annotations:
{{ if eq .Values.spec.ingress.type "nginx" }}
    kubernetes.io/ingress.class: "nginx"
{{ else }}
    #rewrite does not exist yet in ALB
    #https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1571
    #so commenting grouping feature
    #alb.ingress.kubernetes.io/group.name: riker
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  {{ if .Values.spec.ingress.host }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
  {{ else }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
  {{ end }}
    alb.ingress.kubernetes.io/tags: Environment={{ .Values.labels.env }},Team=Riker
{{ end }}
  {{ if .Values.spec.ingress.host }}
    external-dns.alpha.kubernetes.io/set-identifier: {{ .Values.spec.clusterName }}
    external-dns.alpha.kubernetes.io/aws-weight: '{{ .Values.spec.ingress.route53_weight }}'
  {{ end }}    
spec:
{{ if eq .Values.spec.ingress.type "nginx" }}  
  ingressClassName: nginx
{{ else }}
  ingressClassName: alb
{{ end }}
  rules:
  {{ if .Values.spec.ingress.host }}
  - host: cloud-day-app.{{ .Values.spec.ingress.host }}
  {{ else }}
  - host:  
  {{ end }}  
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cloud-day-app
            port: 
              number: 80
